apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  labels:
    app: minio-pv-claim
  spec:
    accessModes: 
    - ReadWriteOnce
    storageClassName: local-storage
    resources:
      requests:
        storage: 50Gi
